In [3]:
#https://github.com/tensorflow/tensorflow
#ติดตั้ง Tensorflow
#1. $ pip install tensorflow
#2. $ pip install tensorflow-cpu
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 3s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ -51.46792  ,  -43.203075 ,    6.4978724,   69.20604  ,
          -7.2439976, -101.78792  ,  -74.11035  ,   42.08808  ,
         -42.017372 ,  152.88225  ]], dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.5696652e-37,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00]], dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

254.67017

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 940us/step - loss: 2.5117 - accuracy: 0.7605
Epoch 2/5
1875/1875 [==============================] - 2s 888us/step - loss: 0.6110 - accuracy: 0.8395
Epoch 3/5
1875/1875 [==============================] - 2s 915us/step - loss: 0.4986 - accuracy: 0.8690
Epoch 4/5
1875/1875 [==============================] - 2s 902us/step - loss: 0.4287 - accuracy: 0.8914
Epoch 5/5
1875/1875 [==============================] - 2s 915us/step - loss: 0.3920 - accuracy: 0.9013


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.3090 - accuracy: 0.9215 - 266ms/epoch - 851us/step


[0.3090318739414215, 0.921500027179718]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.64417575e-37, 2.47622847e-25, 8.59536661e-12, 3.15569253e-07,
        3.97661930e-22, 3.02052158e-24, 0.00000000e+00, 9.99999642e-01,
        0.00000000e+00, 6.68769770e-12],
       [1.88883814e-06, 1.55914109e-02, 9.51650739e-01, 3.19742821e-02,
        2.59455352e-04, 1.14612674e-04, 4.40500880e-05, 9.21956289e-09,
        3.63639963e-04, 3.09937013e-14],
       [3.84504094e-27, 1.00000000e+00, 3.08407158e-16, 3.05016366e-17,
        5.04073519e-11, 4.11926614e-17, 2.32943656e-12, 8.03650702e-10,
        3.40874315e-14, 8.73394356e-23],
       [9.85458851e-01, 2.28244739e-32, 7.72441272e-05, 7.68269092e-05,
        6.21190657e-06, 1.46823202e-03, 1.35449431e-04, 1.25106927e-02,
        2.53431994e-04, 1.30318776e-05],
       [2.05731526e-11, 3.28864358e-09, 1.75088076e-06, 3.48826545e-09,
        9.99966145e-01, 7.37125134e-08, 1.33733091e-09, 3.55774091e-07,
        9.85360349e-10, 3.15622201e-05]], dtype=float32)>